version: "3"

services:
    mybackend:
        image: my-backend
        build: ./api

    myfrontend:
        image: my-frontend
        build: ./frontend

    myloadbalancer:
        image: my-balancer
        build: ./balancer
        ports:
            - "80:80"
        depends_on:
            - mybackend
            - myfrontend
        links:
            - mybackend
            - myfrontend
