version: "3"

services:
    api:
        image: my-backend
        build: ./api
        command: apistar run --port 80 --host 0.0.0.0
        ports:
            - 80
        networks:
            - backend
        environment:
            VIRTUAL_HOST: api.app.dev

    web:
        image: my-frontend
        build: ./frontend
        networks:
            - frontend
        environment:
            VIRTUAL_HOST: app.app.dev

    lb:
        image: dockercloud/haproxy
        ports:
            - '80:80'
        depends_on:
            - api
            - web
        networks:
            - backend
            - frontend
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - api
            - web

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
